import { Manrope } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Navbar";
import Footer from "@/component/Footer";

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Ajay Sethi Business Coach",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${manrope.variable} h-full antialiased`}
    >
      <body
        className="min-h-full flex flex-col dark:bg-white selection:bg-orange-200"
        style={{
          fontFamily: "var(--font-manrope)",
        }}
      >
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}